branches:
  only:
    - master
before_install:
  - git config --global user.name "$USER"
  - git config --global user.email "$TRAVIS_BUILD_NUMBER@$TRAVIS_COMMIT"
  # Decrypt the secret deploy key using instructions from `travis encrypt-file`
  - openssl aes-256-cbc -K $encrypted_ba5ef12f00b3_key -iv $encrypted_ba5ef12f00b3_iv -in project/travis-deploy-key.enc -out project/travis-deploy-key -d
  - chmod 600 project/travis-deploy-key
  # Start ssh-agent in the background and load the deploy key
  - eval "$(ssh-agent -s)"
  - ssh-add project/travis-deploy-key
notifications:
  email:
    recipients:
      - github@quadstingray.com
script:
  - echo ''
os: linux
addons:
  apt:
    packages:
      - oracle-java8-installer
jobs:
  include:
    - stage: SBT Test
      name: "Test with OpenJDK 8"
      language: scala
      os: linux
      jdk: openjdk8
      script: 'sbt +test'
    - stage: SBT Test
      name: "Test with OpenJDK 11"
      language: scala
      os: linux
      jdk: openjdk11
      script: 'sbt +test'
    - stage: SBT Publish
      language: scala
      os: linux
      jdk: openjdk8
      script: '/bin/bash "$TRAVIS_BUILD_DIR/.travis.publish.sh"'
    - stage: Release and Build Docu
      language: scala
      os: linux
      jdk: openjdk8
      script: '/bin/bash "$TRAVIS_BUILD_DIR/.travis.release.sh"'
